#include "chars.h"

namespace Chars {

namespace {

static const CharMap chars{
    {
        '0',
        {
            bitset<CHAR_WIDTH>("011"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
        },
    },
    {
        '1',
        {
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("011"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
        },
    },
    {
        '2',
        {
            bitset<CHAR_WIDTH>("110"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("111"),

        },
    },
    {
        '3',
        {
            bitset<CHAR_WIDTH>("110"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("110"),
        },
    },
    {
        '4',
        {
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
        },
    },
    {
        '5',
        {
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("110"),
        },
    },
    {
        '6',
        {
            bitset<CHAR_WIDTH>("011"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
        },
    },
    {
        '7',
        {
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),

        },
    },
    {
        '8',
        {
            bitset<CHAR_WIDTH>("011"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
        },
    },
    {
        '9',
        {
            bitset<CHAR_WIDTH>("011"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("111"),
        },
    },
    {
        'A',
        {
            bitset<CHAR_WIDTH>("011"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
        },
    },
    {
        'B',
        {
            bitset<CHAR_WIDTH>("110"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("110"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("110"),
        },
    },
    {
        'C',
        {
            bitset<CHAR_WIDTH>("011"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("011"),
        },
    },
    {
        'D',
        {
            bitset<CHAR_WIDTH>("110"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("110"),
        },
    },
    {
        'E',
        {
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("110"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("111"),
        },
    },
    {
        'F',
        {
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("110"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
        },
    },
    {
        'G',
        {
            bitset<CHAR_WIDTH>("011"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("011"),
        },
    },
    {
        'H',
        {
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
        },
    },
    {
        'I',
        {
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
        },
    },
    {
        'J',
        {
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("010"),
        },
    },
    {
        'K',
        {
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("110"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
        },
    },
    {
        'L',
        {
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("111"),
        },
    },
    {
        'M',
        {
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
        },
    },
    {
        'N',
        {
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
        },
    },
    {
        'O',
        {
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("010"),
        },
    },
    {
        'P',
        {
            bitset<CHAR_WIDTH>("110"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("110"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
        },
    },
    {
        'Q',
        {
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("010"),
        },
    },
    {
        'R',
        {
            bitset<CHAR_WIDTH>("110"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("110"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
        },
    },
    {
        'S',
        {
            bitset<CHAR_WIDTH>("011"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("110"),
        },
    },
    {
        'T',
        {
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
        },
    },
    {
        'U',
        {
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
        },
    },
    {
        'V',
        {
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
        },
    },
    {
        'W',
        {
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("101"),
        },
    },
    {
        'X',
        {
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
        },
    },
    {
        'Y',
        {
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("101"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
        },
    },
    {
        'Z',
        {
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("111"),
        },
    },
    {
        ' ',
        {
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
        },
    },
    {
        '.',
        {
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
        },
    },
    {
        ',',
        {
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("100"),
        },
    },
    {
        '-',
        {
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("111"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
        },
    },
    {
        '\\',
        {
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("000"),
        },
    },
    {
        '/',
        {
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("001"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("100"),
            bitset<CHAR_WIDTH>("000"),
        },
    },
    {
        ':',
        {
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
        },
    },
    {
        ';',
        {
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("000"),
            bitset<CHAR_WIDTH>("010"),
            bitset<CHAR_WIDTH>("100"),
        },
    },
};

};

void put_char(PixelData *data, char c, int x, int y, uint8_t color) {
  const Char &char_data = chars.at(c);
  for (int j = 0; j < CHAR_HEIGHT; j++) {
    for (int i = 0; i < CHAR_WIDTH; i++) {
      if (char_data[j][CHAR_WIDTH - i - 1]) {
        *data[y + j][x + i] = color;
      }
    }
  }
}

}; // namespace Chars
